### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by georgekris** [jetpnix/mb_hud#1]
is not working for me no errors and is not the hud from the photo .  
![Bild_2021-05-17_202622](https://user-images.githubusercontent.com/63805204/118538170-24f06b00-b74e-11eb-9a42-6520c343f378.png)

**Comment by baguscodestudio** [comment]
Did you change anything? The folder name maybe? it should be just drag and drop

**Comment by georgekris** [comment]
nop i dont change names or enything :(

**Comment by baguscodestudio** [comment]
Could you please give me an overview on how you install it? what OS your server is running? what artifact are you running? all should be ok.
