### ISSUE TITLE
Dont seem to show unless i restart it while ingame

### ISSUE THREAD

**Issue by Lannebro** [jetpnix/mb_hud#2]
Only shows after the script is beeing reloaded. Tried having it first and last of my resources.

**Comment by baguscodestudio** [comment]
Any error in F8 or server console?

**Comment by Lannebro** [comment]
No errors, but il check again after ive been to the store. Its weird. I havent tried with only the hud.

**Comment by Lannebro** [comment]
No errors.

**Comment by Lannebro** [comment]
Okey, i have found the scripts thats braking urs. Np_skinshop_v2 and newaccessories.

**Comment by baguscodestudio** [comment]
i see, if i remember correctly esx_newaccessories breaks not just my script but others to like esx_identity.
